name: Unit Tests
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write # only required if `comment: true` was enabled
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v6
        with:
          go-version: 1.21

      - name: Run tests
        run: |
          go mod download
          go get -u github.com/vakenbolt/go-test-report/
          go test -json | go-test-report

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: report.html
          path: test_report.html
          retention-days: 5
          compression-level: 0
