name: Unit Tests
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write # only required if `comment: true` was enabled
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v6
        with:
          go-version: 1.21

      - name: Run tests
        run: |
          go mod download
          go test ./... -json > testresults.json

      - name: Report
        uses: dorny/test-reporter@v2.1.1
        with:
          name: Go Reports
          reporter: golang-json      # Format of test results
          path: testresults.json
          use-actions-summary: true

      - name: check results
        run: |
          printenv
          cat $GITHUB_STEP_SUMMARY
          cat $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: summary.md
          path: $GITHUB_STEP_SUMMARY
          retention-days: 5
